ZING-31498: Replace error level for debug level when not all cache configs are set.
zenoss/zenoss-go-sdk pull request #26
Opened 2023-11-22 13:40 UTC by JuanC1303

2023-11-29 14:57 UTC, ssOleg requested changes
Plese check comments in the ticket.

2023-12-08 14:47 UTC, knightpp requested changes

2023-12-08 14:47 UTC, knightpp commented on endpoint/endpoint.go
> +		maxTTL := time.Duration(0.9 * float64(config.ModelTTL))
Instead of using `config.ModelTTL` please add a new const at the top of the file and use here.

2023-12-12 17:47 UTC, ssOleg approved these changes

2023-12-12 17:53 UTC, merged