add caching functions
zenoss/zenoss-go-sdk pull request #6
Opened 2021-04-08 21:45 UTC by asundaratzenoss

2021-04-09 03:41 UTC, bharatZen requested changes

2021-04-09 12:50 UTC, bharatZen commented
Please add appropriate tests for the compact metrics related changes in the sdk

2021-04-09 16:57 UTC, asundaratzenoss commented on endpoint/endpoint.go
> +func (e *Endpoint) GetCacheKey(metric *data_receiver.Metric, tenant string) string {
Updated

2021-04-09 17:06 UTC, asundaratzenoss commented on endpoint/endpoint.go
> +func (e *Endpoint) GetCacheKey(metric *data_receiver.Metric, tenant string) string {
Updated

2021-04-09 17:06 UTC, asundaratzenoss commented on endpoint/endpoint.go
> +	v1, v2 := hash.Sum128()
Updated

2021-04-09 21:59 UTC, asundaratzenoss commented on endpoint/endpoint.go
> +	jm := jsonpb.Marshaler{Indent: "  "}
Updated

2021-04-09 22:08 UTC, asundaratzenoss commented
> Please add appropriate tests for the compact metrics related changes in the sdk
Now only calling ConvertMetrics from outside library, so added test for the same

2021-04-12 22:07 UTC, bharatZen approved these changes

2021-04-13 14:51 UTC, merged